version: 1
build:
  binary: tbdd
  proto:
    path: proto
accounts:
- name: alice
  coins:
  - 2000000000000000000000000utbd
- name: bob
  coins:
  - 2000000000000000000000000utbd
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 1000000000000000utbd
  host: 0.0.0.0:4500
validators:
- name: alice
  bonded: 100000000000000000000000utbd
- name: bob
  bonded: 100000000000000000000000utbd
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: utbd
    staking:
      params:
        bond_denom: utbd
        historical_entries: "10"
        max_validators: "10"
        unbonding_time: 300000000000ns
  chain_id: tbd-local-1